helm_deploy/values-dev.yaml
server/config.ts
server/data/index.ts
server/data/orchestrationApiClient.test.ts
server/data/orchestrationApiClient.ts
server/data/restClient.ts
server/data/testutils/mocks.ts
server/routes/index.test.ts
server/routes/index.ts
server/routes/testutils/appSetup.ts
server/routes/testutils/testData.ts
server/services/index.ts
server/services/supportedPrisonsService.test.ts
server/services/supportedPrisonsService.ts
server/services/testutils/mocks.ts
server/views/pages/index.njk
server/views/pages/prisons.njk

Add support for calling the Orchestration Service API and make a test call (to list supported prison IDs).
Code and config, including for tests, etc brought over from Staff and Admin UI apps.
Purpose is to demonstrate that calling APIs with credentials is still working given HMPPS Auth login replaced with GOV.UK One Login - and that testing set up still works. Will help inform what lingering auth code can be removed.

VB-2554 Add test API call

---

helm_deploy/hmpps-book-a-prison-visit-ui/Chart.yaml
helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml

This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `9 => 1 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …

Migrating project to use groups in allowlist

---

integration_tests/e2e/govukOneLogin.cy.ts
integration_tests/index.d.ts
integration_tests/support/commands.ts
server/@types/express/index.d.ts
server/authentication/govukOneLogin.ts
server/middleware/setUpGovukOneLogin.ts

If a user wasn't logged in to GOV.UK One Login and they requested a specific URL within the application they would end up on the home page `"/"` after log in.
This fixes the issue; restoring functionality that was in the HMPPS Auth implementation in the template app.

VB-3567 Redirect user to originally requested URL after log in

---

README.md
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-staging.yaml
server/authentication/govukOneLogin.ts
server/config.ts
server/utils/nunjucksSetup.ts

Enables setting VTR to a lower level for local, dev and staging environments. This means that users authenticating are not prompted for a second factor code/SMS. (See docs: https://docs.sign-in.service.gov.uk/before-integrating/choose-the-level-of-authentication/#choose-the-level-of-authentication-for-your-service)
Also, some tidying of config for the OL home page URL.

Enable setting GOVUK One Login VTR to low for local / dev environments

---

integration_tests/e2e/bookingJourney.cy.ts
server/routes/bookingJourney/selectVisitorsController.test.ts
server/views/pages/bookingJourney/selectVisitors.njk

Remove unnecessary comma between visitor name and visitor age on select visitors page.

VB-3725 Fix unnecessary commas on visitor list

---

integration_tests/e2e/bookingJourney.cy.ts
integration_tests/pages/bookingJourney/selectVisitDateTimeNoSessions.ts
server/routes/bookingJourney/selectVisitDateTimeController.test.ts
server/routes/bookingJourney/selectVisitDateTimeController.ts
server/views/pages/bookingJourney/selectVisitDateTimeNoSessions.njk

When there are no available visit sessions, show a drop-out page instead of the calendar.

VB-3811 Choose date and time - no visit sessions drop-out page

---

server/@types/bapv.d.ts
server/@types/orchestration-api.d.ts
server/data/orchestrationApiClient.test.ts
server/data/orchestrationApiClient.ts
server/data/orchestrationApiTypes.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/checkVisitDetailsController.ts
server/routes/bookVisit/index.ts
server/routes/bookVisit/mainContactController.test.ts
server/routes/bookVisit/mainContactController.ts
server/routes/testutils/testData.ts
server/services/bookerService.test.ts
server/services/visitService.test.ts
server/services/visitService.ts
server/utils/utils.test.ts
server/views/pages/bookVisit/mainContact.njk

* Simplify how main contact data is stored in the booking journey session data (and update test coverage for this)
* call 'change' application endpoint to update the application when the main contact page is submitted
* call 'book' application endpoint when check visit details page submitted and store the relevant visit data ready for the confirmation page

VB-3944 Update visit application and book visit

---

server/@types/express/index.d.ts
server/routes/bookVisit/selectVisitorsController.test.ts
server/routes/bookVisit/selectVisitorsController.ts

* When going back to the Select visitors page within a journey, pre-populate it with existing session data
* New form data overrides this
* Use the `express-validator` `matchedData()` function rather than `req.body` to avoid potentially storing unexpected user data in the session

VB-3945 Pre-populate Select visitors page with session data when returning

---

server/routes/bookVisit/additionalSupportController.test.ts
server/routes/bookVisit/additionalSupportController.ts

* When going back to the Additional support page within a journey, pre-populate it with existing session data - with new form data overriding this

VB-3947 Pre-populate Additional support page with session data when returning

---

integration_tests/mockApis/orchestration.ts
server/@types/orchestration-api.d.ts
server/data/orchestrationApiClient.test.ts
server/data/orchestrationApiClient.ts
server/routes/bookVisit/chooseVisitTimeController.test.ts
server/routes/bookVisit/chooseVisitTimeController.ts
server/services/visitService.test.ts
server/services/visitService.ts
server/services/visitSessionsService.test.ts
server/services/visitSessionsService.ts
server/views/pages/bookVisit/chooseVisitTime.njk

* Pre-populate page based on previously selected session date/time
* if there is an existing application, pass its reference via `excludedApplicationReference` parameter to ensure it is included as an available visit session
* When choosing a time:
* first time: call 'create application' endpoint to get a new application
* subsequently: call 'change application' endpoint to update the existing application with the selected time

VB-3946 Pre-populate Choose visit time page with session data when returning

---

integration_tests/e2e/bookingJourney.cy.ts
server/constants/dateFormats.ts
server/routes/bookVisit/checkVisitDetailsController.ts
server/services/visitSessionsService.ts
server/utils/nunjucksSetup.ts
server/views/pages/bookVisit/checkVisitDetails.njk
server/views/pages/bookVisit/chooseVisitTime.njk

* Fix integration test failure because of hard-coded test date (Cypress tests run using actual time)
* Small refactor of `DateFormats` constant and add to `app.locals` for re-use within templates

Improve date formatting (and fix integration test bug)

---

integration_tests/e2e/staticContentPages.cy.ts
integration_tests/pages/accessibilityStatement.ts
integration_tests/pages/page.ts
server/app.ts
server/constants/paths.ts
server/middleware/setUpGovukOneLogin.ts
server/routes/testutils/appSetup.ts
server/routes/unauthenticatedRoutes.test.ts
server/routes/unauthenticatedRoutes.ts
server/views/autherror.njk
server/views/pages/accessibilityStatement.njk
server/views/partials/layout.njk

* Set up a set of routes that are loaded before `authenticate()` middleware run so these pages can be viewed by both authenticated and unauthenticated users
* Configure page layout to show GOVUK One Login header for logged in users and fallback header for others
* Unit and integration tests

VB-3851, VB-3885 Set up static content pages for viewing when not logged in

---

assets/js/disableButtonOnSubmit.js
integration_tests/pages/bookVisit/checkVisitDetails.ts
integration_tests/pages/bookVisit/chooseVisitTime.ts
integration_tests/pages/page.ts
server/views/pages/bookVisit/checkVisitDetails.njk
server/views/pages/bookVisit/chooseVisitTime.njk

Disable submit buttons when clicked at key points in the journey to avoid the risk of 'double bookings', e.g. if user attempts to re-try because response is slow.
Applies to: choosing slot on calendar page (i.e. visit application creation) and check details page (i.e. visit booking).
Based on similar changes to Staff UI (https://github.com/ministryofjustice/book-a-prison-visit-staff-ui/pull/766)

VB-3783, VB-3944 Disable submit buttons on submit (create & book)

---

helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-staging.yaml

* Replace deprecated `internal` IP group (see https://github.com/ministryofjustice/hmpps-ip-allowlists)
* add (temporarily) an IP to staging for pen testing

Update IP allow lists and add pen test IP

---

server/authentication/govukOneLogin.ts
server/middleware/setUpGovukOneLogin.ts
server/middleware/setUpWebSecurity.ts

Fixes an issue where if a user had an expired session then tried a form submission it would fail - and appear to 'hang' - because the resultant redirect to re-authenticate with GOV.UK One Login would be blocked by the browser for violating the CSP policy.

VB-4183 Update CSP 'formAction' to include GOV.UK One Login URL

---

server/middleware/setUpWebSecurity.ts

Add '`signin`' as well as the '`oidc`' sub-domain for the GOV.UK One Login URL to the CSP `form-action` rule.
Needed because with an expired session, when a user makes a `POST` request, Chrome blocks the initial redirect to the `oidc` domain and then the subsequent redirect to the `signin` domain.

VB-4183 CSP form-action fix

---

integration_tests/e2e/bookingJourney.cy.ts
integration_tests/e2e/bookingJourneyDropOuts.cy.ts
package-lock.json
package.json
server/@types/orchestration-api.d.ts
server/authentication/govukOneLogin.ts
server/constants/paths.ts
server/data/orchestrationApiClient.ts
server/data/orchestrationApiTypes.ts
server/errorHandler.test.ts
server/errorHandler.ts
server/middleware/setUpGovukOneLogin.ts
server/routes/bookVisit/cannotBookController.test.ts
server/routes/bookVisit/cannotBookController.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/checkVisitDetailsController.ts
server/sanitisedError.ts
server/views/pages/bookVisit/chooseVisitTimeNoSessions.njk
server/views/pages/bookVisit/visitBooked.njk
server/views/pages/error.njk
server/views/pages/signedOut.njk

* Update to handle potential HTTP `422` response and validation error codes when making the API call to 'book' an application 
* Small refactor to split up some integration tests to separate files
Also:
* fix issue with when `res.locals.user` is populated
* update content on error page
* minor tweaks to paths and link visited states

VB-3580 Handle book application error response codes (no VOs or no capacity)

---

integration_tests/e2e/govukOneLogin.cy.ts
integration_tests/e2e/staticContentPages.cy.ts
integration_tests/mockApis/govukOneLogin.ts
integration_tests/pages/page.ts
integration_tests/pages/signedOut.ts
server/authentication/govukOneLogin.ts
server/constants/paths.ts
server/data/hmppsAuthClient.test.ts
server/data/index.ts
server/data/tokenStore/redisTokenStore.test.ts
server/data/tokenStore/redisTokenStore.ts
server/data/tokenStore/tokenStoreFactory.ts
server/errorHandler.ts
server/middleware/populateCurrentBooker.test.ts
server/middleware/populateCurrentBooker.ts
server/middleware/setUpGovukOneLogin.ts
server/views/accessDenied.njk
server/views/authError.njk
server/views/pages/signedOut.njk
server/views/partials/layout.njk

Implement the `post_logout_redirect` GOV.UK One Login functionality (documented [here](https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/managing-your-users-sessions/#log-your-user-out-of-gov-uk-one-login)) so that when a user signs out they are ultimately redirected back to `/sign-out` on our service. The previous behaviour was to end-up with a 'signed-out' page on One Login's domain.
Includes:
* refactor of `TokenStore` and a new `tokenStoreFactory` to get either an in-memory or Redis store with a customisable key prefix. This is needed because a user's `id_token` needs to be stored when they log in so that it is available for use in the log out process
* update of One Login wiremock endpoints to handle storing the `id_token` across requests
* tidy of remaining …

VB-3853, VB-4056 Use GOV.UK One Login post_logout_redirect for user sign out

---

integration_tests/e2e/cookieConsent.cy.ts
integration_tests/pages/cookiesPage.ts
integration_tests/pages/page.ts
server/middleware/analyticsConsent.test.ts
server/routes/cookiesController.test.ts
server/routes/testutils/appSetup.ts
server/views/partials/cookieBanner.njk
server/views/partials/layout.njk

Follow-up to #131:
* Unit tests for cookie consent page
* Unit tests for `analyticsConsent` middleware
* Cypress tests for cookie banner and accepting/rejecting
* Checks cookie is set and that Google Analytics is loaded (or not) as appropriate

VB-4265 Add tests for Cookie banner and cookie consent

---

assets/js/cookieBanner.js
integration_tests/e2e/cookieConsent.cy.ts
integration_tests/e2e/futureVisits.cy.ts
integration_tests/e2e/govukOneLogin.cy.ts
integration_tests/pages/cookiesPage.ts
integration_tests/pages/page.ts
server/routes/cookiesController.test.ts
server/routes/cookiesController.ts
server/views/partials/layout.njk

If a user has previously accepted Google Analytics but then subsequently chooses to reject it, they are left with `_ga and _ga_[containerId]` cookies still set.
This change removes these two cookies when analytics consent is declined, either by the form on the Cookies page (so it's done server-side) or via the cookie banner (so done client-side).

VB-4264 Remove analytics cookies when declining cookie consent

---

.circleci/config.yml

Add the new e2e tests to our public UI service for better coverage on merges to main.

Add UI e2e tests for better coverage on main changes

---

server/@types/bapv.d.ts
server/middleware/bookVisitSessionValidator.test.ts
server/middleware/bookVisitSessionValidator.ts
server/routes/bookVisit/additionalSupportController.test.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/chooseVisitTimeController.test.ts
server/routes/bookVisit/chooseVisitTimeController.ts
server/routes/bookVisit/closedVisitController.test.ts
server/routes/bookVisit/mainContactController.test.ts
server/routes/bookVisit/selectVisitorsController.test.ts
server/routes/bookVisit/selectVisitorsController.ts
server/views/pages/bookVisit/chooseVisitTime.njk

If the visit booking is going to be `CLOSED`, make the Back link on Choose visit time page go back to the closed visit interruption card page. For `OPEN` go back to Select visitors page.

VB-4415 Choose visit time page - update back link for CLOSED visit

---

server/@types/bapv.d.ts
server/@types/orchestration-api.d.ts
server/middleware/bookVisitSessionValidator.test.ts
server/middleware/bookVisitSessionValidator.ts
server/routes/bookVisit/additionalSupportController.test.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/chooseVisitTimeController.test.ts
server/routes/bookVisit/closedVisitController.test.ts
server/routes/bookVisit/mainContactController.test.ts
server/routes/bookVisit/selectVisitorsController.test.ts
server/routes/bookVisit/selectVisitorsController.ts
server/routes/testutils/testData.ts
server/services/bookerService.test.ts
server/services/bookerService.ts
server/services/visitService.test.ts

* List of permitted visitors for a booker/prisoner now includes `visitorRestrictions` for each visitor. Currently the only `BAN` is included
* Refactor to filter only visitors with no restrictions for use during **booking journey** 
* Rename `allVisitors` in the `bookingJourney` session data to be `eligibleVisitors` for clarity

VB-4504 Update handling of Visitors to incorporate visitorRestrictions

---

integration_tests/e2e/bookingJourney.cy.ts
integration_tests/e2e/bookingJourneyDropOuts.cy.ts
integration_tests/e2e/visitors.cy.ts
integration_tests/pages/bookVisit/mainContact.ts
integration_tests/pages/bookVisit/selectVisitors.ts
server/routes/bookVisit/mainContactController.test.ts
server/routes/bookVisit/selectPrisonerController.ts
server/routes/bookVisit/selectVisitorsController.test.ts
server/routes/bookVisit/selectVisitorsController.ts
server/routes/homeController.test.ts
server/routes/testutils/testData.ts
server/services/bookerService.test.ts
server/services/bookerService.ts

In web forms, a `displayId` is used for Prisoner and Visitor objects. This is to avoid using the real database ID. 
Previously, this value was just a sequential integer. This change uses a UUID instead for these values.
(Actual code change very small and pretty much just in `server/services/bookerService.ts` - rest is updating tests...)

VB-4199 Use UUIDs for Prisoner and Visitor display IDs

---

server/@types/express/index.d.ts
server/routes/bookings/bookingDetailsController.test.ts
server/routes/bookings/bookingDetailsController.ts
server/routes/bookings/bookingsController.test.ts
server/routes/bookings/bookingsController.ts
server/routes/bookings/index.ts
server/routes/testutils/testData.ts
server/services/visitService.test.ts
server/services/visitService.ts
server/views/pages/bookings/cancelled.njk
server/views/pages/bookings/future.njk
server/views/pages/bookings/past.njk
server/views/pages/bookings/visit.njk

For bookings listing pages of future / past / cancelled visits, individual visits are referenced by a URL parameter. To avoid using the actual visit reference, this was previously just a sequential integer.
This change is to instead use a UUID as a URL parameter to reference a temporary cache of visits in the session.
Additionally, refactoring of controllers for booking listings and booking details to remove duplication.

VB-4199 Use UUIDs for referencing visit bookings in URL parameters

---

assets/scss/local.scss
server/views/pages/bookings/cancelled.njk
server/views/pages/bookings/future.njk
server/views/pages/bookings/past.njk
server/views/pages/bookings/visit.njk

Updated pages to remove the H2 that were not in the original designs.

VB-4536 - Remove h2 from cancelled visits and past visits page in public service

---

server/routes/bookings/bookingDetailsController.test.ts
server/routes/bookings/bookingDetailsController.ts
server/views/partials/howToChangeBooking.njk

Hide cancel visit button when visit is already cancelled
(Visits in the past already don't display the button)
Fix logic on the howToChangeBooking import, to deal with 'visit details page' and the 'future visits list page'
Both of these don't have the 'bookingConfirmed' object, so this PR deals with the different available visit references, and outputs them IF that line should be displayed

Hide cancel visit button when visit is already cancelled

---

server/routes/unauthenticatedRoutes.test.ts
server/views/authError.test.ts
server/views/partials/layout.njk

We need to implement the new “service navigation” component alongside the new simplified GOV.UK Header component in the public service.
[Service navigation – GOV.UK Design System (design-system.service.gov.uk)](https://design-system.service.gov.uk/components/service-navigation/)
[GOV.UK header – GOV.UK Design System (design-system.service.gov.uk)](https://design-system.service.gov.uk/components/header/)
We also need to move elements currently in the Header component into the new “Service navigation” component. 
GDS will retire the ‘old’ Header in a future break changes version of the Design System.
---
There are some pages in the new public service that we need to update - particularly if they are being viewed by users who are NOT signed in to the service. These are:
* cookies page
* …

VB-4524 Add service navigation when user not signed in

---

server/views/partials/howToChangeBooking.njk

Cancellations can now be done in the service so no need to refer bookers to other journeys to cancel a visit.

Removed reference to cancelling

---

integration_tests/e2e/bookingJourney.cy.ts
integration_tests/e2e/bookingJourneyDropOuts.cy.ts
integration_tests/e2e/bookings.cy.ts
integration_tests/pages/bookVisit/checkVisitDetails.ts
integration_tests/pages/bookVisit/contactDetails.ts
integration_tests/pages/bookVisit/mainContact.ts
integration_tests/pages/bookVisit/visitBooked.ts
integration_tests/pages/page.ts
package-lock.json
package.json
server/@types/bapv.d.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/checkVisitDetailsController.ts
server/routes/bookVisit/contactDetailsController.test.ts
server/routes/bookVisit/visitBookedController.test.ts
server/routes/bookings/bookingDetailsController.test.ts
server/routes/testutils/testData.ts
server/services/visitService.test.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/bookVisit/visitBooked.njk

* Add `libphonenumber-js` as a dependency in order to be able to determine if numbers are mobile or not
* Update Visit booked confirmation page to
* handle different messages depending on contact details provided (email/phone/both/neither)
* distinguish between mobile and other numbers so "text message will be sent" displayed only if a mobile number was supplied
* Update integration tests for new Contact details page

VB-4839 Update visit booked page

---

integration_tests/e2e/govukOneLogin.cy.ts
integration_tests/mockApis/govukOneLogin.ts
server/authentication/govukOneLogin.ts
server/constants/paths.ts
server/middleware/setUpGovukOneLogin.ts

Calls to `passport.authenticate()` in the `/auth/callback` route can fail if, for example, multiple attempts are made with the same parameters (`code, state`), or, if expired ones are used. Evidence in logs of this happening to users, possibly from, e.g. returning to stale browser tabs.
This change adds a callback to handle the response (whether successful or not) for `passport.authenticate()`. This means that errors in the authentication flow can be logged and handled appropriately by redirecting the user to either the sign-in or authentication error page. Previously errors would just trigger the default error handler resulting in an `HTTP 500` response with a default server error page.
(Similar approach to that used in a few other projects, e.g. …

VB-4907 Improve handling of authentication errors

---

server/@types/bapv.d.ts
server/middleware/bookVisitSessionValidator.test.ts
server/middleware/bookVisitSessionValidator.ts
server/routes/bookVisit/cannotBookController.test.ts
server/routes/bookVisit/cannotBookController.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/checkVisitDetailsController.ts
server/routes/bookVisit/selectPrisonerController.test.ts
server/routes/bookVisit/selectPrisonerController.ts
server/views/pages/bookVisit/cannotBook.njk

Refactor the 'A visit cannot be booked page' and associated controller/middleware to work with an extensible set of `CannotBookReason` values - initially just `NO_VO_BALANCE` supported.

VB-4362 Refactor cannot book page to handle different scenarios

---

integration_tests/e2e/bookingJourney.cy.ts
integration_tests/e2e/bookingJourneyDropOuts.cy.ts
integration_tests/e2e/visitors.cy.ts
integration_tests/mockApis/orchestration.ts
integration_tests/pages/bookVisit/cannotBook.ts
server/@types/bapv.d.ts
server/routes/bookVisit/cannotBookController.test.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/checkVisitDetailsController.ts
server/routes/bookVisit/index.ts
server/routes/bookVisit/selectPrisonerController.test.ts
server/routes/bookVisit/selectPrisonerController.ts
server/routes/testutils/testData.ts
server/services/bookerService.test.ts
server/services/bookerService.ts
server/views/pages/bookVisit/cannotBook.njk

When starting a booking journey, call the new validate booker/prisoner endpoint and if this fails (because a prisoner has been transferred or released) redirect to the drop-out page.
Also redirect to the same drop-out page if a prisoner transfer/release is caught at the end of a booking journey (via the `APPLICATION_INVALID_PRISON_PRISONER_MISMATCH` code thrown when booking).

VB-4362 Redirect to Cannot book page if prisoner has been transferred/released

---

server/authentication/govukOneLogin.ts

`opened-client` version `5.7.1` (https://github.com/panva/openid-client/releases/tag/v5.7.1) broke One Login integration because it no longer sent the expected `aud` value in the JWT assertion.
This fix makes sure the expected value (as documented [here](https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/authenticate-your-user/#create-a-jwt)) is present.

Fix following openid-client update

---

integration_tests/e2e/govukOneLogin.cy.ts
integration_tests/e2e/serviceStartPage.cy.ts
integration_tests/pages/serviceStart.ts
integration_tests/support/commands.ts
server/authentication/govukOneLogin.ts
server/constants/paths.ts
server/routes/bookVisit/chooseVisitTimeController.test.ts
server/routes/bookVisit/visitBookedController.ts
server/routes/bookings/bookingDetailsController.ts
server/routes/bookings/bookingsController.ts
server/routes/bookings/cancel/cancelConfirmedController.ts
server/routes/bookings/cancel/cancelController.ts
server/routes/cookiesController.ts
server/routes/homeController.ts
server/routes/unauthenticatedRoutes.test.ts
server/routes/unauthenticatedRoutes.ts
server/routes/visitors/visitorsController.ts
server/views/pages/bookVisit/selectVisitors.njk
server/views/pages/serviceStart.njk
server/views/partials/layout.njk

* Unauthenticated users initially see a new service start page when arriving at the root `/` URL. The 'Start now' button takes them through the normal sign-in flow.
* Authenticated users go straight to the services 'home' page (now actually moved to `/home`)

VB-4380 Service start page

---

feature.env
helm_deploy/values-dev.yaml
integration_tests/e2e/govukOneLogin.cy.ts
integration_tests/e2e/serviceStartPage.cy.ts
server/config.ts
server/constants/paths.ts
server/routes/homeController.test.ts
server/routes/homeController.ts
server/views/pages/home.njk

* Add feature flag for enabling the 'add a prisoner' journey (enabled in dev only)
* If feature enabled, redirect a booker with no prisoners to the journey start instead of the home page when they log in. (This will be a 404 at the moment)

VB-5353 Set up feature flag and redirect for adding a prisoner to a booker

---

integration_tests/e2e/serviceStartPage.cy.ts
integration_tests/mockApis/orchestration.ts
integration_tests/pages/serviceStart.ts
server/@types/orchestration-api.d.ts
server/app.ts
server/data/orchestrationApiClient.test.ts
server/data/orchestrationApiClient.ts
server/data/orchestrationApiTypes.ts
server/routes/testutils/appSetup.ts
server/routes/testutils/testData.ts
server/routes/unauthenticatedRoutes.test.ts
server/routes/unauthenticatedRoutes.ts
server/services/prisonService.test.ts
server/services/prisonService.ts
server/views/pages/serviceStart.njk

Use new endpoint that returns list of supported prison IDs and names for the service. Avoids hard-coding two existing prisons and will be needed for 'Add a prisoner' journey.

VB-5116 Get dynamic list of supported prisons

---

server/routes/addPrisoner/prisonerDetailsController.ts

Prisoner first/last name being escaped unnecessarily causing it to be double-escaped if user goes back to page (Nunjucks is already escaping it).

VB-5117 Add prisoner details - remove unnecessary escaping

---

integration_tests/e2e/bookingJourney.cy.ts
integration_tests/mockApis/orchestration.ts
server/@types/orchestration-api.d.ts
server/data/orchestrationApiClient.test.ts
server/data/orchestrationApiClient.ts
server/routes/bookVisit/checkVisitDetailsController.test.ts
server/routes/bookVisit/checkVisitDetailsController.ts
server/routes/testutils/testData.ts

**Only** if the `FEATURE_VISIT_REQUEST` flag is enabled (currently just dev & staging):
* Update to use available sessions V2 endpoint
* `sessionForReview` flag for selected visiting session stored in booking journey
* `isRequestBooking` flag passed in Dto when calling `/book` endpoint at end of journey

VB-5699 Handle 'sessionForReview' flag and pass when booking

---

integration_tests/mockApis/orchestration.ts
integration_tests/mockApis/prisonRegister.ts
server/data/dataCache/dataCache.ts
server/data/dataCache/inMemoryDataCache.test.ts
server/data/dataCache/inMemoryDataCache.ts
server/data/dataCache/redisDataCache.test.ts
server/data/dataCache/redisDataCache.ts
server/data/index.ts
server/data/orchestrationApiClient.test.ts
server/data/orchestrationApiClient.ts
server/data/orchestrationApiTypes.ts
server/data/prisonRegisterApiClient.test.ts
server/data/prisonRegisterApiClient.ts
server/data/testutils/mocks.ts
server/routes/testutils/testData.ts
server/routes/unauthenticatedRoutes.ts
server/services/index.ts
server/services/prisonService.test.ts
server/services/prisonService.ts
server/services/testutils/mocks.ts

* Add simple cache for JSON data, with Redis and in-memory versions. (Based on similar existing TokenStore implementation)
* Add service methods for getting all prison names and identifying if a prison is supported in the service (to be used on forthcoming select a prison page)
N.B. none of this code is used yet: it's to support upcoming features.

VB-5724 Add data caching and prisons service methods

---

server/middleware/setUpGovukOneLogin.ts

Fix for unhandled error when `/sign-in` is called with `HTTP HEAD`. More info here: https://github.com/panva/openid-client/discussions/613

VB-5789 Fix error for /sign-in on HTTP HEAD request

---

feature.env
integration_tests/redis/redisHelpers.ts
server/config.ts
server/data/dataCache/redisDataCache.test.ts
server/data/dataCache/redisDataCache.ts
server/data/index.ts

When running locally, `dataCache_` entries in Redis creating during Cypress tests were colliding with those created when running the app for local development.
This change derives `dataCache` in `config.ts` so it can be overridden in `feature.env`.
(This change doesn't affect the app when deployed: it still uses `dataCache_<short-git-ref>:` so that cache is cleared on deploying a new version of the app.)

Tweak dataCache prefix

---

server/routes/bookVisit/chooseVisitTimeController.test.ts
server/routes/bookVisit/chooseVisitTimeController.ts

Fix bug where choose date/time calendar page would break when returning to it during booking journey because previously selected visit session no longer available (e.g. because of a change of visitors affecting available sessions).

VB-5816 Handle selected session no longer being available

---

server/views/partials/layout.njk

Spotted a minor but of extraneous code that was stopping the GOV.UK link working correctly in the header.

Fix to header link

---

server/views/pages/bookings/visit.njk

During testing, we noticed that the "Visit/request booking details" page was incorrectly set to full width. This PR fixes it to 2/3 width in line with the other pages.

Fixing incorrect page width

---

assets/scss/local.scss
integration_tests/e2e/visitors.cy.ts
server/@types/bapv.d.ts
server/routes/bookVisit/selectVisitorsController.test.ts
server/routes/bookVisit/selectVisitorsController.ts
server/routes/testutils/testData.ts
server/routes/visitors/visitorsController.test.ts
server/routes/visitors/visitorsController.ts
server/routes/visitors/visitorsUtils.test.ts
server/routes/visitors/visitorsUtils.ts
server/services/bookerService.test.ts
server/services/bookerService.ts
server/views/pages/bookVisit/selectVisitors.njk
server/views/pages/visitors/visitors.njk

If a visitor has multiple overlapping `BAN` restrictions, the API processes these so only a single `BAN` would be received with the furthest (or indefinite) expiry date. This means code handling visitor `BAN`s can be removed/simplified.
Also:
* simplify some types
* switch to building GOVUK Table rows in utility function to simplify template code

VB-3571 Simplify and refactor handling of visitor bans

---

server/routes/bookVisit/chooseVisitTimeController.test.ts
server/routes/bookVisit/chooseVisitTimeController.ts
server/views/pages/bookVisit/chooseVisitTime.njk

On the 'Choose visit time' (calendar) page, add inset text component with details of visitor ban(s) that are affecting the available sessions shown.
If multiple visitors with bans are selected only the visitor(s) with the ban expiring last are shown.

VB-4876 Add visitor ban details to Choose visit time page

---

README.md
helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml
server/app.ts
server/config.ts
server/routes/cookies/cookiesController.test.ts
server/routes/maintenancePageRoute.test.ts
server/routes/maintenancePageRoute.ts
server/routes/staticPages/staticPages.test.ts
server/routes/testutils/appSetup.ts
server/views/pages/maintenancePage.njk
server/views/partials/layout.njk

Add maintenance page with service unavailable page (with optional end date and time).
Maintenance page is controlled by environment variables that can be set via Helm config or edited manually via `kubectl` (documented in the `README`).

VB-5963 Add service maintenance page
