integration_tests/support/commands.ts
Integration tests have been a bit flakey in CircleCI. Hoping this _might_ resolve it 🤞
=> Fix for flakey integration tests

assets/js/init-service-header.js, assets/js/service-header.js, assets/scss/application.scss, assets/scss/components/service-header-no-imports.scss, package-lock.json, package.json, server/routes/index.test.ts, server/views/components/one_login_header/service-header.njk, server/views/components/one_login_header/template.njk, server/views/partials/layout.njk
Add one login header to the project, including basic unit tests
GOV.UK One Login service header repo: https://github.com/govuk-one-login/service-header
=> VB-3475 add one login header

assets/js/vsipCalendar.js, assets/scss/application.scss, assets/scss/components/vsipCalendar.scss, package-lock.json, package.json, server/app.ts, server/routes/calendarPreview.ts, server/utils/nunjucksSetup.ts, server/utils/utils.ts, server/views/pages/calendarPreview.njk, server/views/partials/layout.njk
Preview available on the dev environment: https://visit-dev.prison.service.justice.gov.uk/calendar-preview
=> VB-3555 Basic booking calendar implementation

package-lock.json, package.json, server/@types/bapv.d.ts, server/routes/bookingJourney/index.ts, server/routes/bookingJourney/selectDateAndTimeController.ts, server/routes/bookingJourney/selectVisitorsController.ts, server/utils/nunjucksSetup.test.ts, server/utils/nunjucksSetup.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/bookingJourney/dateAndTimeController.ts, server/views/pages/bookingJourney/selectDateAndTime.njk, server/views/pages/bookingJourney/selectVisitors.njk, server/views/pages/home.njk, server/views/partials/layout.njk
Initial PR - testing not included
=> VB-3725 Select visitors page

README.md, server/@types/bapv.d.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/data/orchestrationApiTypes.ts, server/routes/homeController.ts, server/routes/testutils/testData.ts, server/services/bookerService.ts
Pull in latest API changes - mainly renaming various `Dto`s.
=> VB-3792 Incorporate API updates to get prisonCode for prisoners

server/routes/bookingJourney/selectVisitorsController.test.ts, server/routes/bookingJourney/selectVisitorsController.ts
Add a `customSanitizer()` to the validation chain when selecting visitors to remove any visitor IDs that don't match the list of all visitors.
=> VB-3725 Filter invalid visitor IDs

integration_tests/e2e/bookingJourney.cy.ts, integration_tests/mockApis/orchestration.ts, integration_tests/pages/bookingJourney/selectVisitors.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/data/orchestrationApiTypes.ts, server/routes/bookingJourney/index.ts, server/routes/bookingJourney/selectDateAndTimeController.ts, server/routes/testutils/testData.ts, server/services/index.ts, server/services/testutils/mocks.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts, server/views/pages/bookingJourney/selectDateAndTime.njk
* Add basic client and service layer implementations to get available visit sessions for a prison / prisoner / visitors selection
* So far just dump out the retrieved data
=> VB-3535 Retrieve available visit sessions

server/@types/bapv.d.ts, server/routes/bookingJourney/selectPrisonerController.test.ts, server/routes/bookingJourney/selectPrisonerController.ts, server/routes/homeController.test.ts, server/routes/testutils/testData.ts, server/services/bookerService.test.ts, server/services/bookerService.ts, server/views/pages/home.njk
Hide prisoner number from page source
=> VB-3872, prisoner number hidden

.circleci/config.yml, helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml, helm_deploy/values-prod.yaml
Config for Helm and CircleCI to enable deployment to the production environment.
=> VB-3820 Set up prod environment

helm_deploy/hmpps-book-a-prison-visit-ui/Chart.yaml, helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml
* Configure `mod_security` for all environments in blocking mode, with blocked requests logged
* Add `X-Robots-Tag` with `noindex` and `nofollow`
=> VB-3566 Enable WAF (mod_security) and add X-Robots-Tag

integration_tests/e2e/bookingJourney.cy.ts, integration_tests/mockApis/orchestration.ts
* Stubs now all in place for booking journey
* Actual page tests to be fleshed out when the pages are fully built
=> VB-3944 Add wiremock stubs for change/book visit endpoints

helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml, server/middleware/setUpWebSession.ts
* Updates to WAF rules
* rename session cookie
=> VB-3980 Update mod_security rules to stop false positives

server/@types/bapv.d.ts, server/@types/express/index.d.ts, server/routes/bookVisit/additionalSupportController.test.ts, server/routes/bookVisit/chooseVisitTimeController.test.ts, server/routes/bookVisit/mainContactController.test.ts, server/routes/bookVisit/selectVisitorsController.test.ts, server/routes/testutils/appSetup.ts
Small refactor to hopefully improve how flash is typed and mocked in tests.
=> VB-3945 Refactor handling of flash in tests

server/@types/bapv.d.ts, server/routes/bookVisit/additionalSupportController.test.ts, server/routes/bookVisit/checkVisitDetailsController.test.ts, server/routes/bookVisit/checkVisitDetailsController.ts, server/routes/bookVisit/chooseVisitTimeController.test.ts, server/routes/bookVisit/chooseVisitTimeController.ts, server/routes/bookVisit/mainContactController.test.ts, server/services/visitService.test.ts, server/services/visitService.ts, server/services/visitSessionsService.test.ts, server/services/visitSessionsService.ts, server/utils/nunjucksSetup.ts, server/views/pages/bookVisit/checkVisitDetails.njk
Add allVisitSessions and selectedVisitSession to bookingJourney data object
Display all visit details and back links on 'check visit details' page
=> VB-3481, visit details page, get route

helm_deploy/values-dev.yaml, helm_deploy/values-staging.yaml, server/routes/bookVisit/additionalSupportController.ts, server/utils/nunjucksSetup.ts, server/views/pages/bookVisit/additionalSupport.njk
To make it easier for tests to integrate with the testing helper API.
=> Add application reference as a test attribute (dev & staging)

server/@types/bapv.d.ts, server/constants/paths.ts, server/middleware/bookVisitSessionValidator.test.ts, server/middleware/bookVisitSessionValidator.ts, server/routes/bookVisit/additionalSupportController.test.ts, server/routes/bookVisit/additionalSupportController.ts, server/routes/bookVisit/checkVisitDetailsController.test.ts, server/routes/bookVisit/checkVisitDetailsController.ts, server/routes/bookVisit/chooseVisitTimeController.test.ts, server/routes/bookVisit/chooseVisitTimeController.ts, server/routes/bookVisit/index.ts, server/routes/bookVisit/mainContactController.test.ts, server/routes/bookVisit/mainContactController.ts, server/routes/bookVisit/selectPrisonerController.test.ts, server/routes/bookVisit/selectPrisonerController.ts, server/routes/bookVisit/selectVisitorsController.test.ts, server/routes/bookVisit/selectVisitorsController.ts, server/routes/homeController.test.ts, server/routes/index.ts, server/utils/nunjucksSetup.ts, server/views/pages/bookVisit/additionalSupport.njk, server/views/pages/bookVisit/checkVisitDetails.njk, server/views/pages/bookVisit/chooseVisitTime.njk, server/views/pages/bookVisit/chooseVisitTimeNoSessions.njk, server/views/pages/bookVisit/mainContact.njk, server/views/pages/bookVisit/selectVisitors.njk, server/views/pages/home.njk
Two main changes:
* Add a new `paths` constant to hold route paths. This avoids them being repeated across code and tests. It's also added to `app.locals` so is available in templates.
* New `bookVisitSessionValidator` middleware to check the necessary is in the user's session at each stage in the journey
Also test updates to cover the above.
=> VB-3861 Add session validation middleware for booking journey

integration_tests/e2e/staticContentPages.cy.ts, integration_tests/pages/privacyPolicy.ts, integration_tests/pages/termsAndConditions.ts, server/constants/paths.ts, server/routes/homeController.test.ts, server/routes/unauthenticatedRoutes.test.ts, server/routes/unauthenticatedRoutes.ts, server/views/pages/accessibilityStatement.njk, server/views/pages/privacyPolicy.njk, server/views/pages/termsAndConditions.njk, server/views/partials/layout.njk
* Add phase banner to all pages
* Add Footer component links
* Static content pages:
* Accessibility statement 
* Privacy policy
* Terms and conditions
=> VB-3854, VB-3885, VB-3852, VB-3984, VB-3985 Add static page content

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-staging.yaml, server/config.ts, server/middleware/setUpWebSecurity.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk
* Add tracking code JS and necessary CSP directives
* Configure prod account ID and in all other environments use the non-prod account
=> VB-3856 Add Google Analytics

server/routes/bookVisit/mainContactController.test.ts, server/routes/bookVisit/mainContactController.ts
Refactor and improve validation on Main contact page:
* Expand test data
* Check that when selecting a visitor as a main contact that it is both a valid selected visitor ID and  an adult visitor
* Refactor `express-validator` code to be simpler and use more built-in functions
=> VB-3479 Refactor and tighten main contact validation

helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml
Temporarily disable WAF for testing.
=> Disable WAF

.circleci/config.yml
Just moving over the alerts channel
=> Change Slack alerts channel

server/routes/bookVisit/additionalSupportController.test.ts, server/utils/nunjucksSetup.test.ts
Add test coverage for changes in #82 (adding support for showing extra test data attributes in DEV and STAGING).
=> Add tests for extra testing attributes

integration_tests/e2e/staticContentPages.cy.ts, integration_tests/pages/privacyNotice.ts, integration_tests/pages/privacyPolicy.ts, server/constants/paths.ts, server/routes/unauthenticatedRoutes.test.ts, server/routes/unauthenticatedRoutes.ts, server/views/pages/accessibilityStatement.njk, server/views/pages/bookVisit/checkVisitDetails.njk, server/views/pages/bookVisit/chooseVisitTime.njk, server/views/pages/bookVisit/chooseVisitTimeNoSessions.njk, server/views/pages/bookVisit/mainContact.njk, server/views/pages/bookVisit/selectVisitors.njk, server/views/pages/bookings/index.njk, server/views/pages/home.njk, server/views/pages/privacyNotice.njk, server/views/pages/privacyPolicy.njk, server/views/pages/termsAndConditions.njk
* Update text of Privacy notice
* Small refactor of how page titles are handled in all templates to remove duplication of content
=> VB-3984 Update Privacy notice

server/views/pages/bookVisit/selectVisitors.njk
Added link to new booker form and confirmed it is 5 working days for a response. Fixes VB-4181.
=> Update for VB-4181

server/views/pages/bookVisit/additionalSupport.njk, server/views/pages/bookVisit/selectVisitors.njk
Tiny content updates spotted during texting - ticket VB-4182
=> Small content fixes for VB-4182

server/routes/bookVisit/additionalSupportController.test.ts, server/routes/bookVisit/mainContactController.test.ts, server/views/pages/bookVisit/additionalSupport.njk, server/views/pages/bookVisit/mainContact.njk
=> Fix page headings and titles

server/views/pages/bookings/index.njk
Temporarily remove the links to view past/cancelled visits until these pages are built.
=> VB-4196 Remove past/cancelled links

server/constants/paths.ts, server/routes/unauthenticatedRoutes.test.ts, server/routes/unauthenticatedRoutes.ts, server/views/authError.njk, server/views/pages/signedOut.njk
Signed out page, just view and basic route
=> VB-3853, signed out page view

helm_deploy/values-prod.yaml
Make prod service available without IP restrictions
=> VB-4234 Remove IP allowlist in prod

helm_deploy/values-staging.yaml
=> VB-4241 Fix whitespace issue in helm config

server/@types/express/index.d.ts, server/constants/paths.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/routes/bookings/bookingDetailsController.test.ts, server/routes/bookings/bookingDetailsController.ts, server/routes/bookings/bookingsController.test.ts, server/routes/bookings/bookingsController.ts, server/routes/bookings/index.ts, server/services/visitService.test.ts, server/services/visitService.ts, server/views/pages/bookings/cancelled.njk, server/views/pages/bookings/future.njk, server/views/pages/bookings/past.njk, server/views/pages/bookings/visit.njk
Draft PR 
List Past and Cancelled visit pages
Add necessary parts to the visit details page to deal with both Cancelled and Past visits
=> VB-3615/VB-3616/VB-3617/VB-3618/ Future and Cancelled visits views

server/errorHandler.test.ts, server/errorHandler.ts, server/views/pages/error.njk
Update error page content
remove error code if in production
=> VB-4339, update error page content

server/@types/bapv.d.ts, server/constants/paths.ts, server/middleware/bookVisitSessionValidator.test.ts, server/middleware/bookVisitSessionValidator.ts, server/routes/bookVisit/additionalSupportController.test.ts, server/routes/bookVisit/cannotBookController.ts, server/routes/bookVisit/checkVisitDetailsController.test.ts, server/routes/bookVisit/chooseVisitTimeController.test.ts, server/routes/bookVisit/chooseVisitTimeController.ts, server/routes/bookVisit/closedVisitController.test.ts, server/routes/bookVisit/mainContactController.test.ts, server/routes/bookVisit/selectPrisonerController.ts, server/routes/bookVisit/selectVisitorsController.test.ts, server/routes/bookVisit/selectVisitorsController.ts, server/routes/homeController.test.ts, server/routes/homeController.ts, server/routes/index.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/bookVisit/chooseVisitTime.njk, server/views/pages/bookVisit/closedVisit.njk
Add a route to clear session and redirect back to home when abandoning journey on the closed visit interruption card.
Also, refactor to use this session clearing method in other places.
=> VB-3815 Clear session when abandoning journey

helm_deploy/values-staging.yaml
For accessibility audit access.
=> VB-4324 Turn off allowlist for staging environment

package-lock.json, package.json, server/middleware/setUpWebSession.ts, server/routes/bookVisit/selectVisitorsController.test.ts, server/routes/bookVisit/selectVisitorsController.ts, server/services/bookerService.test.ts, server/services/bookerService.ts, server/services/visitService.test.ts, server/services/visitService.ts
* Remove `uuid` dependency and use Node's `crypto.randomUUID()` (as advised on https://www.npmjs.com/package/uuid)
* Update Select visitors validation code to use `express-validator`'s `isUUID()` validation
=> VB-4199 Remove 'uuid' dependency and replace with crypto.randomUUID()

server/@types/orchestration-api.d.ts, server/routes/testutils/testData.ts
Code tidy following API changes.
=> VB-4527 Remove excludeDates from PrisonDto

server/routes/bookVisit/visitBookedController.ts, server/views/pages/bookVisit/visitBooked.njk, server/views/pages/bookings/future.njk, server/views/pages/bookings/visit.njk, server/views/partials/howToChangeBooking.njk
Remove duplication for "How to change your booking" text (and fix an inconsistency between the three instances of it).
=> VB-4336 Remove duplication for change booking text

helm_deploy/hmpps-book-a-prison-visit-ui/values.yaml
Add more modsec rules to avoid false positives
=> Update Modsec rules

integration_tests/pages/bookings/cancelledVisitsPage.ts, integration_tests/pages/bookings/index.ts, integration_tests/pages/bookings/pastVisitsPage.ts, server/@types/orchestration-api.d.ts, server/constants/paths.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/data/orchestrationApiTypes.ts, server/routes/bookings/bookingDetailsController.ts, server/routes/bookings/bookingsController.test.ts, server/routes/bookings/cancelVisitController.test.ts, server/routes/bookings/cancelVisitController.ts, server/routes/bookings/index.ts, server/services/visitService.test.ts, server/services/visitService.ts, server/views/pages/bookings/cancel/cancel.njk, server/views/pages/bookings/cancel/cancelConfirmation.njk, server/views/pages/bookings/cancelled.njk, server/views/pages/bookings/future.njk, server/views/pages/bookings/past.njk, server/views/pages/bookings/visit.njk
Add cancel journey for booker made visits
Show cancel option until the start of the visit
=> VB-4469, Booker cancel visit journey

integration_tests/pages/bookVisit/visitBooked.ts, server/routes/bookVisit/visitBookedController.test.ts, server/views/pages/bookVisit/visitBooked.njk, server/views/partials/howToChangeBooking.njk
Add new content to booking confirmation page
=> VB-4471, booking confirmation page content changes

server/routes/bookings/bookingDetailsController.test.ts, server/views/pages/bookings/visit.njk
Add 'You cancelled this visit' to the visit summary page - including test
=> VB-4467, update cancelled visit summary

integration_tests/e2e/bookingJourney.cy.ts, integration_tests/e2e/bookingJourneyDropOuts.cy.ts, server/@types/bapv.d.ts, server/constants/paths.ts, server/middleware/bookVisitSessionValidator.test.ts, server/middleware/bookVisitSessionValidator.ts, server/routes/bookVisit/checkVisitDetailsController.test.ts, server/routes/bookVisit/checkVisitDetailsController.ts, server/routes/bookVisit/contactDetailsController.test.ts, server/routes/bookVisit/contactDetailsController.ts, server/routes/bookVisit/index.ts, server/routes/bookVisit/mainContactController.test.ts, server/routes/bookVisit/mainContactController.ts, server/services/visitService.test.ts, server/services/visitService.ts, server/views/pages/bookVisit/contactDetails.njk, server/views/pages/bookVisit/mainContact.njk
* Remove phone number fields from existing Main contact page
* New Contact details page to (optionally) capture main contact email address and/or phone number
* Update tests and session checking middleware
(Integration tests and other stages of the journey will be updated to reflect new email option in subsequent PRs.)
=> VB-4837 New Contact details page (for main contact email & phone)

integration_tests/e2e/bookings.cy.ts, integration_tests/e2e/cancelBookingJourney.cy.ts, integration_tests/mockApis/orchestration.ts, integration_tests/pages/bookings/cancelConfirmationPage.ts, integration_tests/pages/bookings/cancelConfirmedPage.ts, integration_tests/pages/bookings/cancelVisitPage.ts, integration_tests/pages/bookings/visit.ts
Add integration test for booker cancel journey and banner on a booker cancelled visit
=> VB-4786 booker cancellation integration

integration_tests/e2e/visitors.cy.ts, integration_tests/pages/visitors/visitors.ts, server/routes/visitors/visitorsController.test.ts, server/views/pages/visitors/visitors.njk
Made some minor improvements to the Visitors page, including:
* remove back link to match other 'main' pages
* updating page title to 'Visitors'
* updating related tests
=> Minor updates to the Visitors page

server/routes/bookVisit/checkVisitDetailsController.test.ts, server/routes/bookVisit/checkVisitDetailsController.ts, server/routes/bookings/bookingDetailsController.ts, server/views/pages/bookVisit/checkVisitDetails.njk, server/views/pages/bookVisit/contactDetails.njk
Update Check visit details page to separate 'main contact' and 'contact details.
=> VB-4873 Update Check visit details page

integration_tests/e2e/bookings.cy.ts, integration_tests/e2e/cookieConsent.cy.ts, integration_tests/e2e/govukOneLogin.cy.ts, integration_tests/e2e/staticContentPages.cy.ts, integration_tests/index.d.ts, integration_tests/pages/bookings/visit.ts, integration_tests/support/commands.ts, server/@types/orchestration-api.d.ts, server/routes/bookings/bookingDetailsController.test.ts, server/routes/testutils/testData.ts, server/views/pages/bookings/visit.njk
* Add email address if present when viewing a visit's details
* (Unrelated: tweak integration tests to hide cookie banner by default)
=> VB-4790 Show main contact email address on visit details

server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/data/orchestrationApiTypes.ts, server/services/bookerService.test.ts, server/services/bookerService.ts
* Add API call to validate prisoner for given booker
* `validatePrisoner()` method in `BookerService` to return `true | false`
=> VB-4362 Add 'validate prisoner' API endpoint

integration_tests/e2e/bookingJourneyDropOuts.cy.ts, integration_tests/mockApis/orchestration.ts, integration_tests/pages/bookVisit/cannotBook.ts, server/@types/bapv.d.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiTypes.ts, server/routes/bookVisit/cannotBookController.test.ts, server/routes/bookVisit/selectPrisonerController.test.ts, server/routes/bookVisit/selectPrisonerController.ts, server/routes/testutils/testData.ts, server/services/bookerService.test.ts, server/services/bookerService.ts, server/views/pages/bookVisit/cannotBook.njk
* Updates for changes in format of `HTTP 422` error response
* Prisoner now has details of **registered** as well as current prison. Show registered prison details on 'cannot book' page
=> VB-4362 Incorporate API changes and use 'registered' prison details

integration_tests/e2e/bookings.cy.ts, integration_tests/e2e/cancelBookingJourney.cy.ts, server/routes/bookings/bookingDetailsController.test.ts, server/routes/bookings/bookingDetailsController.ts, server/routes/bookings/bookingsController.test.ts, server/routes/bookings/bookingsController.ts, server/routes/bookings/index.ts, server/services/bookerService.test.ts, server/services/bookerService.ts, server/views/pages/bookings/future.njk, server/views/pages/bookings/visit.njk, server/views/partials/prisonerTransferOrReleaseBanner.njk
On these pages:
* future visits listing
* future visit details
show an information banner if the prisoner has been released or transferred from the prison they are registered to in the service.
=> VB-4909, VB-4910 Show info banner if prisoner transferred or released

server/@types/orchestration-api.d.ts, server/data/orchestrationApiTypes.ts, server/routes/testutils/testData.ts, server/services/bookerService.ts
`convictedStaus` moving within `BookerPrisonerInfoDto`.
=> VB-5328 'convictedStatus' Dto change

integration_tests/e2e/govukOneLogin.cy.ts, integration_tests/e2e/serviceStartPage.cy.ts, server/@types/bapv.d.ts, server/@types/express/index.d.ts, server/routes/addPrisoner/index.ts, server/routes/addPrisoner/prisonerLocationController.test.ts, server/routes/addPrisoner/prisonerLocationController.ts, server/routes/homeController.test.ts, server/routes/homeController.ts, server/routes/index.ts, server/utils/nunjucksSetup.ts, server/views/pages/addPrisoner/prisonerLocation.njk, server/views/pages/home.njk
* Remove auto redirect to add prisoner journey if booker has no prisoner: instead keep on service 'home' page with an 'Add prisoner' button
* Add Prisoner location page with choice of supported prisons (`GET` route only so far)
=> VB-5116 Add a prisoner: select prison page

helm_deploy/values-staging.yaml, server/routes/addPrisoner/index.ts, server/routes/addPrisoner/prisonerLocationController.test.ts, server/routes/addPrisoner/prisonerLocationController.ts, server/routes/bookVisit/additionalSupportController.ts, server/routes/bookVisit/contactDetailsController.ts, server/routes/bookVisit/mainContactController.ts, server/views/pages/addPrisoner/prisonerLocation.njk
* Handle selection of prisoner location, validate and store in session
* Enable add prisoner feature in staging
=> VB-5116 Add prisoner - select location POST route and validation

server/routes/addPrisoner/prisonerLocationController.test.ts, server/routes/addPrisoner/prisonerLocationController.ts, server/views/pages/addPrisoner/prisonerLocation.njk, server/views/pages/bookVisit/additionalSupport.njk, server/views/pages/bookVisit/cannotBook.njk, server/views/pages/bookVisit/checkVisitDetails.njk, server/views/pages/bookVisit/chooseVisitTime.njk, server/views/pages/bookVisit/chooseVisitTimeNoSessions.njk, server/views/pages/bookVisit/closedVisit.njk, server/views/pages/bookVisit/contactDetails.njk, server/views/pages/bookVisit/mainContact.njk, server/views/pages/bookVisit/selectVisitors.njk, server/views/pages/bookVisit/visitBooked.njk, server/views/pages/bookings/cancel/cancel.njk, server/views/pages/bookings/cancel/cancelConfirmed.njk, server/views/pages/bookings/cancelled.njk, server/views/pages/bookings/future.njk, server/views/pages/bookings/past.njk, server/views/pages/bookings/visit.njk, server/views/pages/error.njk, server/views/pages/home.njk, server/views/partials/layout.njk
* If prisoner's prison ID has been selected then pre-populate this if returning to the prisoner location page.
* Simplify Nunjucks import paths
=> VB-5116 Add prisoner: pre-populate selected prison when returning to prisoner location page

server/views/pages/bookVisit/cannotBook.njk
Small PR to update the "find a prisoner" content to match what is being developed in VB-4547.
=> updated text to match new content

server/@types/bapv.d.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts, server/data/orchestrationApiTypes.ts, server/routes/addPrisoner/index.ts, server/routes/addPrisoner/prisonerDetailsController.test.ts, server/routes/addPrisoner/prisonerDetailsController.ts, server/routes/addPrisoner/prisonerLocationController.test.ts, server/routes/bookVisit/additionalSupportController.test.ts, server/routes/testutils/testData.ts, server/services/bookerService.test.ts, server/services/bookerService.ts, server/views/pages/addPrisoner/prisonerDetails.njk, server/views/pages/bookVisit/mainContact.njk
* Add API support for registering a prisoner for a booker
* 'Prisoner details' page and form validations
* Redirects to success/fail pages (not yet built - follow-on tickets)
=> VB-5117 Add prisoner: enter prisoner details page

server/@types/bapv.d.ts, server/routes/addPrisoner/index.ts, server/routes/addPrisoner/prisonerAddedController.test.ts, server/routes/addPrisoner/prisonerAddedController.ts, server/routes/addPrisoner/prisonerDetailsController.test.ts, server/routes/addPrisoner/prisonerDetailsController.ts, server/routes/addPrisoner/prisonerLocationController.test.ts, server/routes/addPrisoner/prisonerLocationController.ts, server/routes/addPrisoner/prisonerNotMatchedController.test.ts, server/routes/addPrisoner/prisonerNotMatchedController.ts, server/views/pages/addPrisoner/prisonerAdded.njk, server/views/pages/addPrisoner/prisonerNotMatched.njk
* small refactor to `addPrisonerJourney` session data to store prison details instead of just IDs (because name needed on failure page)
* add the success and failure pages
=> VB-5118, VB-5119 Add prisoner: success and failure pages

server/routes/addPrisoner/prisonerDetailsController.test.ts, server/routes/addPrisoner/prisonerDetailsController.ts, server/routes/addPrisoner/prisonerLocationController.test.ts, server/routes/addPrisoner/prisonerLocationController.ts
* Ensure day/month padded with leading zero if < 10
* Fix to ensure prisoner details are retained in session if going back to change prisoner location
=> VB-5117 Add prisoner: date of birth validation fix

server/routes/addPrisoner/prisonerDetailsController.test.ts, server/views/pages/error.njk, server/views/pages/serviceStart.njk
Spotted a couple of small text changes.
=> Minor text tweaks

integration_tests/e2e/addPrisoner.cy.ts, integration_tests/mockApis/orchestration.ts, integration_tests/pages/addPrisoner/prisonerAdded.ts, integration_tests/pages/addPrisoner/prisonerDetails.ts, integration_tests/pages/addPrisoner/prisonerLocation.ts, integration_tests/pages/addPrisoner/prisonerNotMatched.ts, integration_tests/pages/home.ts
Add in integration tests (Cypress) for the 'Add a prisoner' journey
=> VB-5388 Add prisoner integration tests

server/routes/visitors/visitorsController.test.ts, server/views/pages/bookVisit/selectVisitors.njk, server/views/pages/visitors/visitors.njk
Updates two public screens:
* Who is going on the visit page
* Visitors page
Updated unit tests.
See: https://dsdmoj.atlassian.net/browse/VB-5140
=> Vb 5140 booker with no visitors prompted to add visitor

server/routes/bookVisit/additionalSupportController.test.ts, server/routes/bookVisit/additionalSupportController.ts, server/views/pages/bookVisit/additionalSupport.njk
Switch to using character count component in public service
=> VB-5444, add additional support character count component

assets/scss/components/_visits-spacing.scss, integration_tests/e2e/bookingJourneyDropOuts.cy.ts, integration_tests/e2e/bookings.cy.ts, integration_tests/pages/bookVisit/chooseVisitTime.ts, integration_tests/pages/bookings/visit.ts, integration_tests/pages/page.ts, server/@types/bapv.d.ts, server/@types/express/index.d.ts, server/routes/addPrisoner/prisonerDetailsController.test.ts, server/routes/addPrisoner/prisonerLocationController.test.ts, server/routes/bookVisit/additionalSupportController.test.ts, server/routes/bookVisit/checkVisitDetailsController.test.ts, server/routes/bookVisit/checkVisitDetailsController.ts, server/routes/bookVisit/chooseVisitTimeController.test.ts, server/routes/bookVisit/chooseVisitTimeController.ts, server/routes/bookVisit/contactDetailsController.test.ts, server/routes/bookVisit/mainContactController.test.ts, server/routes/bookVisit/selectVisitorsController.test.ts, server/routes/bookings/bookingDetailsController.test.ts, server/routes/bookings/bookingDetailsController.ts, server/routes/bookings/bookingsUtils.test.ts, server/routes/bookings/bookingsUtils.ts, server/routes/cookiesController.test.ts, server/routes/testutils/appSetup.ts, server/views/pages/bookVisit/chooseVisitTime.njk, server/views/pages/bookings/visit.njk
* Switch to use new MoJ Alert component
* Small refactor of `req.flash()` types for consistency with staff / admin services
=> VB-5396 Replace MoJ Banners with MoJ Alerts

assets/scss/local.scss, server/routes/visitors/visitorsController.test.ts, server/routes/visitors/visitorsController.ts, server/routes/visitors/visitorsUtils.test.ts, server/routes/visitors/visitorsUtils.ts, server/services/bookerService.ts, server/views/pages/visitors/visitors.njk
Add banned visitor tags to visitor listing page
=> VB-4877, add visitors listing page banned tags

server/constants/paths.ts, server/routes/unauthenticatedRoutes.test.ts, server/routes/unauthenticatedRoutes.ts
Add a redirect to PVB as an interim measure. This will ultimately be replaced by a ''Select a prison' page at the same URL.
=> VB-5752 Add path '/select-prison' and redirect to legacy service (PVB)

integration_tests/mockApis/orchestration.ts, server/@types/orchestration-api.d.ts, server/data/orchestrationApiClient.test.ts, server/data/orchestrationApiClient.ts
* Update available sessions endpoint to `/visit-sessions/public/available`
* Remove feature flag wrapping this endpoint
=> Update available sessions API

integration_tests/e2e/bookings.cy.ts, integration_tests/e2e/cancelBookingJourney.cy.ts, integration_tests/pages/bookings/cancel/cancelVisit.ts, server/@types/orchestration-api.d.ts, server/routes/bookings/bookingDetailsController.test.ts, server/routes/bookings/bookingDetailsController.ts, server/routes/bookings/bookingsController.test.ts, server/routes/bookings/bookingsUtils.test.ts, server/routes/bookings/bookingsUtils.ts, server/routes/bookings/cancel/cancelController.test.ts, server/views/pages/bookings/cancel/cancel.njk, server/views/pages/bookings/future.njk, server/views/pages/bookings/visit.njk, server/views/partials/howToChangeBooking.njk, server/views/partials/howToUpdateRequest.njk
* Update text and alert messages to handle a user withdrawing a visit request
* Fix some issues in spotted with #379
=> VB-5880 Handle withdrawn visit requests
